services:
    php:
        build: .
        volumes:
            - ./:/app
        environment:
            MONGODB_URI: 'mongodb://mongodb:27017/test'
        depends_on:
            - mongodb

    mongodb:
        image: mongo
        platform: linux/amd64
        ports:
            - 27017:27017
        volumes:
            - mongodb:/data/db
        command: --storageEngine wiredTiger

volumes:
    mongodb:
